### ISSUE TITLE
jbt failing with TypeError on Linux

### ISSUE THREAD

**Issue by rrix** [thlorenz/lldb-symbolicate#1]
```
{0}% lldb -- /home/rrix/Uber/node/node_g --perf-basic-prof app.js
Current executable set to '/home/rrix/Uber/node/node_g' (x86_64).
(lldb) command script import /bin/jbt.py
break listThe jit symbol resolver command `jbt` has been initialized and is ready for use.
(lldb) break list
Current breakpoints:
1: name = 'v8::internal::PerfBasicLogger::LogRecordedBuffer', locations = 1
    Breakpoint commands:
      return jbt.jit_break(frame, bp_loc, internal_dict)

  1.1: where = node_g`v8::internal::PerfBasicLogger::LogRecordedBuffer(v8::internal::Code*, v8::internal::SharedFunctionInfo*, char const*, int) + 29 at log.cc:285, address = 0x0000000000da94c5, unresolved, hit count = 0 

(lldb) r
Process 13540 launched: '/home/rrix/Uber/node/node_g' (x86_64)
(lldb) Traceback (most recent call last):
  File "temp.py", line 7, in lldb_autogen_python_bp_callback_func__0
  File "/usr/lib/node_modules/lldb-jbt/jbt.py", line 88, in jit_break
    name        = "%.*s" % (length, name_var.GetSummary().strip('"'))
TypeError: * wants int
Process 13540 stopped
* thread #1: tid = 13540, 0x0000000000da94c5 node_g`v8::internal::PerfBasicLogger::LogRecordedBuffer(this=0x0000000003690b20, code=0x00002ff6b1a06001, (null)=0x0000000000000000, name=0x0000000003690b44, length=15) + 29 at log.cc:285, name = 'node_g', stop reason = breakpoint 1.1
    frame #0: 0x0000000000da94c5 node_g`v8::internal::PerfBasicLogger::LogRecordedBuffer(this=0x0000000003690b20, code=0x00002ff6b1a06001, (null)=0x0000000000000000, name=0x0000000003690b44, length=15) + 29 at log.cc:285
   282                                         SharedFunctionInfo*,
   283                                         const char* name,
   284                                         int length) {
-> 285    DCHECK(code->instruction_start() == code->address() + Code::kHeaderSize);
   286 
   287    base::OS::FPrint(perf_output_handle_, "%llx %x %.*s\n",
   288                     reinterpret_cast<uint64_t>(code->instruction_start()),
```

```
{0}% yum info lldb
Loaded plugins: langpacks, refresh-packagekit
Installed Packages
Name        : lldb
Arch        : x86_64
Version     : 3.4
Release     : 12.fc20
Size        : 26 M
Repo        : installed
From repo   : updates
Summary     : Next generation high-performance debugger
URL         : http://llvm.org/
License     : NCSA
Description : LLDB is a next generation, high-performance debugger. It is built as a set
            : of reusable components which highly leverage existing libraries in the
            : larger LLVM Project, such as the Clang expression parser and LLVM
            : disassembler.
```

```
{0}% sudo npm i -g lldb-jbt
[sudo] password for rrix: 
npm http GET https://registry.npmjs.org/lldb-jbt
npm http 200 https://registry.npmjs.org/lldb-jbt
npm http GET https://registry.npmjs.org/lldb-jbt/-/lldb-jbt-0.3.0.tgz
npm http 200 https://registry.npmjs.org/lldb-jbt/-/lldb-jbt-0.3.0.tgz
/bin/jbt -> /lib/node_modules/lldb-jbt/jbt
/bin/jbt.py -> /lib/node_modules/lldb-jbt/jbt.py
lldb-jbt@0.3.0 /lib/node_modules/lldb-jbt
```

**Comment by thlorenz** [comment]
should be fixed now, can you try again?
