### ISSUE TITLE
JBT fails with TypeError on linux

### ISSUE THREAD

**Issue by Willyham** [thlorenz/lldb-symbolicate#2]
willy@localhost:~$ uname -a
Linux localhost.localdomain 3.17.7-300.fc21.x86_64 #1 SMP Wed Dec 17 03:08:44 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

```
(lldb) Traceback (most recent call last):
  File "temp.py", line 7, in lldb_autogen_python_bp_callback_func__0
  File "/home/willy/npm/bin/jbt.py", line 88, in jit_break
    name        = "%.*s" % (length, name_var.GetSummary().strip('"'))
TypeError: * wants int
Process 18836 stopped
* thread #1: tid = 18836, 0x0000000000dba7ef node_g`v8::internal::PerfBasicLogger::LogRecordedBuffer(this=0x0000000002d73af0, code=0x00002f39d0b06681, (null)=0x0000000000000000, name=0x0000000002d73b14, length=20) + 29 at log.cc:285, name = 'node_g', stop reason = breakpoint 1.1
    frame #0: 0x0000000000dba7ef node_g`v8::internal::PerfBasicLogger::LogRecordedBuffer(this=0x0000000002d73af0, code=0x00002f39d0b06681, (null)=0x0000000000000000, name=0x0000000002d73b14, length=20) + 29 at log.cc:285
   282                                         SharedFunctionInfo*,
   283                                         const char* name,
   284                                         int length) {
-> 285    DCHECK(code->instruction_start() == code->address() + Code::kHeaderSize);
   286  
   287    base::OS::FPrint(perf_output_handle_, "%llx %x %.*s\n",
   288                     reinterpret_cast<uint64_t>(code->instruction_start()),
(lldb) 
```

**Comment by thlorenz** [comment]
should be fixed now, can you try again?
